#define NEW_CHEM_CARTRIDGE(X) \
/obj/item/reagent_containers/chem_disp_cartridge/X { \
	spawn_reagent = /datum/reagent/X \
}

NEW_CHEM_CARTRIDGE(aluminium)
NEW_CHEM_CARTRIDGE(bromine)
NEW_CHEM_CARTRIDGE(carbon)
NEW_CHEM_CARTRIDGE(chlorine)
NEW_CHEM_CARTRIDGE(copper)
NEW_CHEM_CARTRIDGE(consumable/ethanol)
NEW_CHEM_CARTRIDGE(fluorine)
NEW_CHEM_CARTRIDGE(hydrogen)
NEW_CHEM_CARTRIDGE(iodine)
NEW_CHEM_CARTRIDGE(iron)
NEW_CHEM_CARTRIDGE(lithium)
NEW_CHEM_CARTRIDGE(mercury)
NEW_CHEM_CARTRIDGE(nitrogen)
NEW_CHEM_CARTRIDGE(oxygen)
NEW_CHEM_CARTRIDGE(phosphorus)
NEW_CHEM_CARTRIDGE(potassium)
NEW_CHEM_CARTRIDGE(uranium/radium)
NEW_CHEM_CARTRIDGE(silicon)
NEW_CHEM_CARTRIDGE(sodium)
NEW_CHEM_CARTRIDGE(stable_plasma)
NEW_CHEM_CARTRIDGE(consumable/sugar)
NEW_CHEM_CARTRIDGE(sulfur)
NEW_CHEM_CARTRIDGE(toxin/acid)
NEW_CHEM_CARTRIDGE(water)
NEW_CHEM_CARTRIDGE(fuel)
