name: Pull Request Labeller

on:
  pull_request:
    branches:
      - master
      - 'project/**'

jobs:
  label_new_pulls:
    name: "Add and Sync PR Labels"
    runs-on: ubuntu-22.04
    steps:
      - uses: fuxingloh/multi-labeler@2.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: ".github/pr_labels.yml"
