name: Pull Request Labeller

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
    branches:
      - spacebar

jobs:
  label_new_pulls:
    name: "Add and Sync PR Labels"
    runs-on: ubuntu-20.04
    steps:
      - uses: fuxingloh/multi-labeler@1d6d95ddcc7ef8b928d514329663ba4e0ff0eaf5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: ".github/pr_labels.yml"
