name: Pull Request Labeller

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
    branches:
      - master
      - 'project/**'

permissions:
  contents: read
  pull-requests: write
  statuses: write
  checks: write

jobs:
  label_new_pulls:
    name: "Add and Sync PR Labels"
    runs-on: ubuntu-22.04
    steps:
      - uses: fuxingloh/multi-labeler@v2.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: ".github/pr_labels.yml"
